---
- hosts: '{{ service }}'
  user: root
  #any_errors_fatal: true
  gather_facts: yes
  strategy: free
  vars:
    - service: ag-chain-cosmos
    - APPDIR: "{{lookup('pipe', 'pwd')}}/../.."
    - HELPER_BINARY: "{{lookup('env', 'GOBIN') or ((lookup('env', 'GOPATH') or '/usr/local') + '/bin')}}/agd"
  roles:
    - stop
    - copy
    - unsafe_reset
    - start
