export {
  REMOTE_STYLE,
  mustPassByPresence,
  getInterfaceOf,
  pureCopy,
  QCLASS,
  getErrorConstructor,
  mustPassByRemote,
  sameValueZero,
  passStyleOf,
  makeMarshal,
  Remotable,
  Far,
  Data,
} from './src/marshal';
