name: Chain deployment test

on:
  # Use the following to explicitly start this workflow.
  # packages/deployment/scripts/start-deployment-test.sh <BRANCH-OR-TAG>
  workflow_dispatch:
  # Otherwise, run on default branch.
  push:
    branches: [ master ] # $default-branch

jobs:
  deployment-test:
    runs-on: ubuntu-18.04 # trusty
    steps:
    - uses: actions/checkout@v2
      with:
        clean: 'false'
    - uses: ./.github/actions/restore-golang
      with:
        go-version: 1.17
    - uses: ./.github/actions/restore-node
      with:
        node-version: 14.x

    # Select a branch on loadgen to test against by adding text to the body of the
    # pull request. For example: #loadgen-branch: user-123-update-foo
    # The default is 'main'
    - name: Get the appropriate loadgen branch
      id: get-loadgen-branch
      uses: actions/github-script@0.9.0
      with:
        result-encoding: string
        script: |
          let branch = 'main';
          if (context.payload.pull_request) {
            const { body } = context.payload.pull_request;
            const regex = /.*\#loadgen-branch:\s+(\S+)/;
            const result = regex.exec(body);
            if (result) {
              branch = result[1];
            }
          }
          console.log(branch);
          return branch;

    - name: Check out loadgen
      uses: actions/checkout@v2
      with:
        repository: Agoric/testnet-load-generator
        path: testnet-load-generator
        ref: ${{steps.get-loadgen-branch.outputs.result}}

    - name: Move repos under /usr/src where scripts expect them
      run: |
        set -e
        sudo mv "$GITHUB_WORKSPACE/testnet-load-generator" /usr/src/testnet-load-generator
        sudo mv "$GITHUB_WORKSPACE" /usr/src/agoric-sdk
        ln -s /usr/src/agoric-sdk/packages/deployment/bin/ag-setup-cosmos /usr/local/bin/ag-setup-cosmos
        ln -s /usr/src/agoric-sdk "$GITHUB_WORKSPACE"
      working-directory: /

    - name: Build cosmic-swingset dependencies
      run: |
        # Some of our build relies on /usr/src/agoric-sdk
        set -e
        cd /usr/src/agoric-sdk/packages/cosmic-swingset
        make install
      working-directory: /
    - run: sudo ./packages/deployment/scripts/install-deps.sh
      working-directory: /usr/src/agoric-sdk
    - run: /usr/src/agoric-sdk/packages/deployment/scripts/integration-test.sh
      env:
        NETWORK_NAME: chaintest
    - name: capture results
      if: failure()
      run: |
        NOW=$(date -u +%Y%m%dT%H%M%S)
        echo "NOW=$NOW" >> "$GITHUB_ENV"

        # Stop the chain from running.
        /usr/src/agoric-sdk/packages/deployment/scripts/setup.sh play stop || true

        # Get the results.
        /usr/src/agoric-sdk/packages/deployment/scripts/capture-integration-results.sh

        # Tear down the nodes.
        echo yes | /usr/src/agoric-sdk/packages/deployment/scripts/setup.sh destroy
      env:
        NETWORK_NAME: chaintest
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: deployment-test-results-${{ env.NOW }}
        path: chaintest/results
