name: PR Checks

# run CI on all PRs (even the ones that target non-default
# branches)

on:
  pull_request:

jobs:
  # Check that commits conform to https://www.conventionalcommits.org/en/v1.0.0/
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # as of v0.16.0 commitsar still requires full git objects, so fetch-depth=0
          # https://github.com/aevea/commitsar/blob/master/www/docs/usage/github.md#actionscheckoutv2
          fetch-depth: 0
      - name: check Conventional Commits
        uses: docker://outillage/commitsar
