name: Test Dapp OTC Desk

# run CI on pushes to default, and on all PRs (even the ones that target other
# branches)

on:
  push:
    branches: [ master ] # $default-branch
  pull_request:

jobs:
  test-dapp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.x']

    steps:

    - name: Checkout agoric-sdk
      uses: actions/checkout@v2
      with:
        path: agoric-sdk
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: agoric-sdk/yarn.lock
    - name: cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('agoric-sdk/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # Select a branch on dapp to test against by adding text to the body of the
    # pull request. For example: #dapp-encouragement-branch: zoe-release-0.7.0
    # The default is 'main'
    - name: Get the appropriate dapp branch
      id: get-branch
      uses: actions/github-script@0.9.0
      with:
        result-encoding: string
        script: |
          let branch = 'main';
          if (context.payload.pull_request) {
            const { body } = context.payload.pull_request;
            const regex = /.*\#dapp-otc-branch:\s+(\S+)/;
            const result = regex.exec(body);
            if (result) {
              branch = result[1];
            }
          }
          console.log(branch);
          return branch;

    - name: yarn install --frozen-lockfile
      run: yarn install --frozen-lockfile
      working-directory: ./agoric-sdk
    # 'yarn build' loops over all workspaces
    - name: yarn build
      run: yarn build
      working-directory: ./agoric-sdk
    - name: yarn link
      run: |
        yarn link-cli ~/bin/agoric
        echo "/home/runner/bin" >> $GITHUB_PATH
      working-directory: ./agoric-sdk

    - name: Check out dapp
      uses: actions/checkout@v2
      with:
        repository: Agoric/dapp-otc
        path: dapp
        ref: ${{steps.get-branch.outputs.result}}

    - name: Agoric install in dapp
      run: agoric install
      working-directory: ./dapp

    - name: yarn build in dapp
      run: yarn build
      working-directory: ./dapp
    
    - name: yarn test in dapp
      run: yarn test
      working-directory: ./dapp
